---
name: HealthLimit
version: 1.0.2
main: NhanAZ\HealthLimit\Main
api: 5.0.0
src-namespace-prefix: NhanAZ\HealthLimit
author: NhanAZ
website: https://github.com/NhanAZ
description: "Make your server harder (or not) by limiting players' health"
...
